CREATE DATABASE PROYECTO_SIA
USE PROYECTO_SIA

CREATE TABLE PROFESOR(
IdProfesor VARCHAR(10) PRIMARY KEY NOT NULL,
TipoDocProfesor VARCHAR(4) NOT NULL,
PrimerNombreProfesor VARCHAR(10) NOT NULL,
SegundoNombreProfesor VARCHAR(10),
PrimerApellidoProfesor VARCHAR(13) NOT NULL,
SegundoApellidoProfesor VARCHAR(13) NOT NULL,
CelularProfesor VARCHAR(10) NOT NULL,
DireccionProfesor VARCHAR(20) NOT NULL,
EmailProfesor VARCHAR(20) NOT NULL,
ContraseñaProfesor VARCHAR(10) NOT NULL,
)

CREATE TABLE MATERIA(
IdMateria VARCHAR(7) PRIMARY KEY NOT NULL,
NombMateria VARCHAR(20) NOT NULL
)

CREATE TABLE ESTUDIANTE(
IdEstudiante VARCHAR(10) PRIMARY KEY NOT NULL,
TipoDocEstudiante VARCHAR(4) NOT NULL,
PrimerNombreEstudiante VARCHAR(10) NOT NULL,
SegundoNombreEstudiante VARCHAR(10),
PrimerApellidoEstudiante VARCHAR(13) NOT NULL,
SegundoApellidoEstudiante VARCHAR(13) NOT NULL,
CelularEstudiante VARCHAR(10) NOT NULL,
DireccionEstudiante VARCHAR(20) NOT NULL,
EmailEstudiante VARCHAR(20) NOT NULL,
ContraseñaEstudiante VARCHAR(10) NOT NULL,
)

CREATE TABLE CURSO(
IdGrupo VARCHAR(10) PRIMARY KEY NOT NULL,
IdMateria VARCHAR(7) NOT NULL,
IdProfesor VARCHAR(10) NOT NULL,
CONSTRAINT PK_MATERIA FOREIGN KEY
(IdMateria) REFERENCES MATERIA (IdMateria),
CONSTRAINT PK_PROFESOR FOREIGN KEY
(IdProfesor) REFERENCES PROFESOR (IdProfesor),
)


CREATE TABLE ASISTENCIA(
IdAsistencia VARCHAR(5) PRIMARY KEY NOT NULL,
IdGrupo VARCHAR(10) NOT NULL,
IdEstudiante VARCHAR(10) NOT NULL,
Fecha DATE NOT NULL,
Estado VARCHAR(8) NOT NULL,
CONSTRAINT PK_CURSO FOREIGN KEY
(IdGrupo) REFERENCES CURSO (IdGrupo),
CONSTRAINT PK_ESTUDIANTE FOREIGN KEY
(IdEstudiante) REFERENCES ESTUDIANTE (IdEstudiante),
)

CREATE TABLE ACTIVIDAD(
IdActividad VARCHAR(3) PRIMARY KEY NOT NULL,
NombreActividad VARCHAR(20) NOT NULL,
IdGrupo VARCHAR(10) NOT NULL,
CONSTRAINT PK_CURS FOREIGN KEY
(IdGrupo) REFERENCES CURSO (IdGrupo),
)

CREATE TABLE NOTA(
IdNota VARCHAR(3) PRIMARY KEY NOT NULL,
IdActividad VARCHAR(3) NOT NULL,
IdEstudiante VARCHAR(10) NOT NULL,
ValorNota DECIMAL(3,2) NOT NULL,
CONSTRAINT PK_ACT FOREIGN KEY
(IdActividad) REFERENCES ACTIVIDAD (IdActividad),
CONSTRAINT PK_EST FOREIGN KEY
(IdEstudiante) REFERENCES ESTUDIANTE (IdEstudiante),
)

CREATE TABLE ESTUDIANTEXGRUPO(
IdEstudiante VARCHAR(10) NOT NULL,
IdGrupo VARCHAR(10) NOT NULL,
CONSTRAINT PK_ESTUDIANTES FOREIGN KEY
(IdEstudiante) REFERENCES ESTUDIANTE (IdEstudiante),
CONSTRAINT PK_CURSOS FOREIGN KEY
(IdGrupo) REFERENCES CURSO (IdGrupo),
)